### ISSUE TITLE
[Feature] v16.13.1 need to support windows os

### ISSUE THREAD

**Issue by jornathanJ** [ng-doc/ng-doc#102]
### Description

Just as Windows OS was supported in v16.12.1
I hope this is also possible in v16.13.1

```bash
# This is error on my project
⠋ NgDoc: Loading entities...
 >  NX   Invalid Unicode escape sequence


SyntaxError: Invalid Unicode escape sequence
    at new Function (<anonymous>)
    at importEsm (C:\ng16\uifw\node_modules\@ng-doc\builder\helpers\import-esm.js:10:12)
    at C:\ng16\uifw\node_modules\@ng-doc\builder\helpers\import-fresh-esm.js:24:57
    at Generator.next (<anonymous>)
    at fulfilled (C:\ng16\uifw\node_modules\tslib\tslib.js:164:62)
```

Also, This is what I've got while build with latest source code on windows.
```bash
>  NX   Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

### Proposed solution

This is work for me, but I didn't make a pull request because it wasn't cool.

```typescript
import Os from 'os'

/**
 * Hacky way to import ES modules dynamically.
 *
 * @param modulePath
 */
export function importEsm<T>(modulePath: string): Promise<T> {
           
  if(Os.platform() === 'win32'){
    const modulePathWin32 = modulePath.substring(2, modulePath.length).replace(/\\/g, '/');
    //Need to change path for windows
    //console.log(modulePathWin32);
    return new Function(`return import('${modulePathWin32}');`)();
  } else {
    return new Function(`return import('${modulePath}');`)();
  }
}
```

### Alternatives considered

None

**Comment by skoropadas** [comment]
Hey, thanks for the issue, I'll fix it today!

**Comment by jornathanJ** [comment]
Great, Thanks!
