### ISSUE TITLE
[Bug] Inline Default Exports Not Supported

### ISSUE THREAD

**Issue by Char2sGu** [ng-doc/ng-doc#237]
### Is this a regression?

No

### Description

In `ng-doc.api.ts`, such declaration causes an error:

```ts
export default {
  title: 'API References',
  scopes: [],
} satisfies NgDocApi;
```

Such inline default exports causes errors in many other NgDoc entries, such as `ng-doc.page.ts` and `ng-doc.category.ts`. However, for `ng-doc.api.ts`, this used to work, but not anymore after upgrading to v18

### Please provide the exception or error you saw

```true
Template render error: (/home/char2s/projects/angularity/node_modules/@ng-doc/builder/templates/context.ts.nunj) [Line 21, Column 47]
  Error: No object expression found in /home/char2s/projects/angularity/docs/src/content/ng-doc.api.ts, make sure the file has a default export.
    at Object._prettifyError (/home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/lib.js:32:11)
    at /home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/environment.js:464:19
    at Template.root [as rootRenderFunc] (eval at _compile (/home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:118:3)
    at Template.render (/home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/environment.js:454:10)
    at /home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/environment.js:301:27
    at createTemplate (/home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/environment.js:254:9)
    at handle (/home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/environment.js:265:11)
    at /home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/environment.js:276:9
    at next (/home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/lib.js:258:7)
    at Object.asyncIter (/home/char2s/projects/angularity/node_modules/@ng-doc/builder/node_modules/nunjucks/src/lib.js:263:3)
```

### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

doesn't matter

**Comment by skoropadas** [comment]
Yes, I would also like to support this, but the problem lies in the Angular compiler. The issue is that NgDoc imports some page configurations directly into the frontend application, for example, to automatically import demo components into your page's component. Essentially, when using such an export, the Angular compiler, for some reason, stops recognizing the components and throws an error. This is the only reason why the syntax looks this way.
