### ISSUE TITLE
[Bug] Not rebuild automatically

### ISSUE THREAD

**Issue by 0xc0000007b** [ng-doc/ng-doc#59]
### Is this a regression?

Yes

### Description

Not rebuild a page automatically  
I creating the page and create the documentation page
if i was edit the page, page don't reloading an me need restart the dev server by stopping batch job and run ng serve again
and ng g @ng-doc/builder:standalone-pages-migration doesn't work

### OS

Windows

### Browser

Other

### Node version

latest

**Comment by fil0157** [comment]
Hello, I work on Windows and in my case changes in .md files are not caught either

**Comment by skoropadas** [comment]
@fil0157 yep this is the windows problem with `minimatch` library, I need to use a bit different pattern to make it work on Windows machines, I'll fix it today.

**Comment by 0xc0000007b** [comment]
> @0xc0000007b sry but few questions:
> 
> * what is the difference between "page" and "documentation page"? do you mean just a simple page with a markdown file?
> * do you have any errors or output in the console after running the migration?
> 
> I think maybe it doesn't work only on Windows, I'll check it, but that's weird because the last few major versions have no changes related to the rebuilding process.

migration was not generate for me. And if i edit my md page page builder was not recompile them for me.. How fix this?

**Comment by skoropadas** [comment]
@0xc0000007b I'll release a new version with the fix soon, just want to check the migration on Windows before it

**Comment by 0xc0000007b** [comment]
> @0xc0000007b I'll release a new version with the fix soon, just want to check the migration on Windows before it

Thank you

**Comment by skoropadas** [comment]
@0xc0000007b new version is releasing, should work now in the 16.3.5 version. 

I also tried to reproduce the issue with migration but it worked well for me, even on Windows, so if it's an issue for you then please share some repo where I can reproduce it.

**Comment by 0xc0000007b** [comment]
> 🎉 This issue has been resolved in version 16.3.5 🎉
> 
> The release is available on:
> 
> * `v16.3.5`
> * [GitHub release](https://github.com/ng-doc/ng-doc/releases/tag/v16.3.5)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

i download latels version of tour library and getting this on starting serving
`NgDoc error: (0 , minimatch_1.minimatch) is not a function
TypeError: (0 , minimatch_1.minimatch) is not a function
    at C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\@ng-doc\builder\engine\watcher.js:34:131
    at Array.some (<anonymous>)
    at C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\@ng-doc\builder\engine\watcher.js:34:93
    at C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\rxjs\dist\cjs\internal\operators\filter.js:9:120
    at OperatorSubscriber._this._next (C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:33:21)    
    at Subscriber.next (C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)
    at C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\rxjs\dist\cjs\internal\Subject.js:69:34
    at Object.errorContext (C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\rxjs\dist\cjs\internal\util\errorContext.js:22:9)
    at Subject.next (C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\rxjs\dist\cjs\internal\Subject.js:59:24)
    at FSWatcher.<anonymous> (C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\@ng-doc\builder\engine\watcher.js:21:44)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher.emitWithAll (C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (C:\Users\AngularDev\Desktop\blog\untitled16\node_modules\chokidar\lib\nodefs-handler.js:637:21)
`

**Comment by skoropadas** [comment]
@0xc0000007b sorry I forgot to update `minimatch` version in the dependencies section of the library, new version will be released in 10 minutes
